Handle v2 format of overlays.json
marzent/IINACT pull request #45
Opened 2023-03-26 22:51 UTC by Orphis

Generate overlay URIs according to the v2 overlay template document.
The new documented process tries to match ws:// and wss:// with secure or plaintext URIs and uses regular .Net methods for URI manipulation when appropriate.

2023-03-26 22:53 UTC, Orphis commented
This obviously depends on a submodule bump for the new overlay file. Since I'm still waiting a bit for comments on those changes, the final SHA isn't known and this won't work as-is.

2023-03-27 19:12 UTC, marzent requested changes

2023-03-27 19:12 UTC, marzent commented on IINACT/Windows/MainWindow.cs
> +        var overlayUri = selectedOverlay.toOverlayUri($"ws://{Server?.Address}:{Server?.Port}/ws");
this needs to be null safe or it will crash if the GUI is drawn before OP is ready

2023-03-27 19:12 UTC, marzent commented on IINACT/Windows/MainWindow.cs
> +        var overlayUriString = overlayUri != null ? overlayUri.ToString() : "<Error generating URI>";
you can use `??` here

2023-03-27 19:12 UTC, marzent commented on OverlayPlugin.Core/OverlayTemplateConfig.cs
> +        public Uri toOverlayUri(string webSocketServer)
would probably be cleaner to pass a `URI` directly

2023-04-05 21:40 UTC, marzent approved these changes

2023-04-05 21:43 UTC, merged